FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o gateway ./cmd/gateway

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/gateway .

EXPOSE 8000

CMD ["./gateway"]
