FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o file-service ./cmd/file-service

FROM alpine:latest

WORKDIR /app

RUN mkdir -p /tmp/file-share

COPY --from=builder /app/file-service .

EXPOSE 8082

CMD ["./file-service"]
