FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o share-service ./cmd/share-service

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/share-service .

EXPOSE 8083

CMD ["./share-service"]
